# Generated by Django 4.1.7 on 2023-04-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_category_img_prduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prduct',
        ),
    ]
