# Generated by Django 4.1.7 on 2023-04-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_shopcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shopcart',
        ),
    ]
