# Generated by Django 4.1.7 on 2023-04-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_payment_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': True, 'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': True, 'verbose_name': 'Payment', 'verbose_name_plural': 'Payment'},
        ),
        migrations.AlterModelOptions(
            name='shopcart',
            options={'managed': True, 'verbose_name': 'Shopcart', 'verbose_name_plural': 'Shopcart'},
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
        migrations.AlterModelTable(
            name='shopcart',
            table='shopcart',
        ),
    ]
