# Generated by Django 4.1.7 on 2023-04-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_profile_firstname_alter_profile_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastName',
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.CharField(default='a', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
