# Generated by Django 4.1.7 on 2023-04-13 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0004_remove_profile_firstname_remove_profile_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='ad', max_length=100)),
                ('last_name', models.CharField(default='ad', max_length=100)),
                ('pix', models.ImageField(default='profile.jpg', upload_to='Profile')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=150)),
                ('nationality', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
