# Generated by Django 4.1.7 on 2023-04-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pix',
            field=models.ImageField(default='avater.jpg', upload_to='Profile'),
        ),
    ]
